AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  AppnameApplesService:
    Type: AWS::Serverless::Api
    Description: "Serverless API for CRUD operations"
    Properties:
      Name: "appname-apples-service"
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS, POST, GET, PUT, DELETE'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'http://localhost:3000'" # replace with frontend app URL

  AppnameApplesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: dist/index.lambdaHandler
      Runtime: nodejs20.x
      Policies:
        - AWSLambdaExecute
        - SecretsManagerReadWrite
        - DynamoDBCrudPolicy:
            TableName: !Ref AppnameApplesTable
      Events:
        ApplesOptions:
          Type: Api
          Properties:
            Path: /apples
            Method: OPTIONS
            RestApiId: !Ref AppnameApplesService
        GetApple:
          Type: Api
          Properties:
            Path: /apples/{id}
            Method: GET
            RestApiId: !Ref AppnameApplesService
        GetApples:
          Type: Api
          Properties:
            Path: /apples
            Method: GET
            RestApiId: !Ref AppnameApplesService
        PutApple:
          Type: Api
          Properties:
            Path: /apples
            Method: POST
            RestApiId: !Ref AppnameApplesService
        DeleteApple:
          Type: Api
          Properties:
            Path: /apples/{id}
            Method: DELETE
            RestApiId: !Ref AppnameApplesService
        UpdateApple:
          Type: Api
          Properties:
            Path: /apples/{id}
            Method: PUT
            RestApiId: !Ref AppnameApplesService
    Metadata:
      BuildMethod: makefile

  AppnameApplesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AppnameApples
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
